from django.db import models


class Brokers(models.Model):
    crd = models.CharField(max_length=5555)
    npm = models.CharField(max_length=5555)
    firstName = models.CharField(max_length=5555)
    middleName = models.CharField(max_length=5555)
    lastName = models.CharField(max_length=5555)
    otherNames = models.CharField(max_length=5555)
    team = models.CharField(max_length=5555)
    brokerDealer = models.CharField(max_length=5555)
    brokerDealerCRD = models.CharField(max_length=5555)
    yearsWithCurrentBD = models.CharField(max_length=5555)
    currentBDStartDate = models.DateTimeField(null=True, blank=True)
    ria = models.CharField(max_length=5555)
    riaCRD = models.CharField(max_length=5555)
    yearsWithCurrentRIA = models.CharField(max_length=5555)
    currentRIAStateDate = models.DateTimeField(null=True, blank=True)
    address = models.CharField(max_length=5555)
    city = models.CharField(max_length=5555)
    state = models.CharField(max_length=5555)
    zip = models.CharField(max_length=5555)
    metroArea = models.CharField(max_length=5555)
    licensesAndExams = models.CharField(max_length=5555)
    title = models.CharField(max_length=5555)
    designations = models.CharField(max_length=5555)
    phone = models.CharField(max_length=5555)
    phone_type = models.CharField(max_length=5555)
    linkedIn = models.CharField(max_length=5555)
    email1 = models.CharField(max_length=5555)
    email2 = models.CharField(max_length=5555)
    email3 = models.CharField(max_length=5555)
    personalEmail = models.CharField(max_length=5555)
    bio = models.CharField(max_length=5555)
    yearsOfExperience = models.CharField(max_length=5555)
    estAge = models.CharField(max_length=5555)
    previousBrokerDealer = models.CharField(max_length=5555)
    previousRIA = models.CharField(max_length=5555)
    gender = models.CharField(max_length=5555)
    teamId = models.CharField(max_length=5555)
    personTagRole = models.CharField(max_length=5555)
    personTagFamily = models.CharField(max_length=5555)
    personTagHobbies = models.CharField(max_length=5555)
    personTagExpertise = models.CharField(max_length=5555)
    personTagServices = models.CharField(max_length=5555)
    personTagInvestments = models.CharField(max_length=5555)
    personTagSportsTeams = models.CharField(max_length=5555)
    personTagSchool = models.CharField(max_length=5555)
    personTagGreekLife = models.CharField(max_length=5555)
    personTagMilitaryStatus = models.CharField(max_length=5555)
    personTagFaithBasedInvesting = models.CharField(max_length=5555)
    firmTagPlatform = models.CharField(max_length=5555)
    firmTagTechnology = models.CharField(max_length=5555)
    firmTagServices = models.CharField(max_length=5555)
    firmTagInvestments = models.CharField(max_length=5555)
    firmTagCustodian = models.CharField(max_length=5555)
    firmTagClients = models.CharField(max_length=5555)
    firmTagCRM = models.CharField(max_length=5555)
    notes = models.CharField(max_length=5555)
    profile = models.CharField(max_length=5555)
    secLink = models.CharField(max_length=5555)
    finraLink = models.CharField(max_length=5555)
    firmCompanyName = models.CharField(max_length=5555)
    firmType = models.CharField(max_length=5555)
    firmAddress = models.CharField(max_length=5555)
    firmCity = models.CharField(max_length=5555)
    firmState = models.CharField(max_length=5555)
    firmZip = models.CharField(max_length=5555)
    firmPhone = models.CharField(max_length=5555)
    firmAUM = models.CharField(max_length=5555)
    firmTotalAccounts = models.CharField(max_length=5555)
    firmCustodians = models.CharField(max_length=5555)
    firmTotalEmployees = models.CharField(max_length=5555)
    firmRIAReps = models.CharField(max_length=5555)
    firmBDReps = models.CharField(max_length=5555)
    firmForm13f = models.CharField(max_length=5555)
    lines = models.CharField(max_length=5555)
    carrier = models.CharField(max_length=5555)
    company = models.CharField(max_length=5555)
    initialAppointmentDate = models.CharField(max_length=5555)
    captive = models.CharField(max_length=5555)
    numOfCarriers = models.CharField(max_length=5555)
    numOfLines = models.CharField(max_length=5555)
    nonProducing = models.CharField(max_length=5555)
    insuranceYearsOfExperience = models.CharField(max_length=5555)

    def __str__(self):
        return f"{self.crd} - {self.firstName} {self.middleName} {self.lastName}"


class BrokersLinkedInProfileData(models.Model):
    broker = models.ForeignKey(Brokers, on_delete=models.CASCADE)
    urn = models.CharField(max_length=5555, null=True, blank=True)
    username = models.CharField(max_length=5555, null=True, blank=True)
    firstName = models.CharField(max_length=5555, null=True, blank=True)
    lastName = models.CharField(max_length=5555, null=True, blank=True)
    isOpenToWork = models.BooleanField(null=True, blank=True)
    isHiring = models.BooleanField(null=True, blank=True)
    profilePicture = models.URLField(null=True, blank=True)
    summary = models.CharField(max_length=5555, null=True, blank=True)
    headline = models.CharField(max_length=5555, null=True, blank=True)
    geo = models.JSONField(null=True, blank=True)
    languages = models.CharField(max_length=5555, null=True, blank=True)
    educations = models.JSONField(null=True, blank=True)
    position = models.JSONField(null=True, blank=True)
    fullPositions = models.JSONField(null=True, blank=True)
    skills = models.JSONField(null=True, blank=True)
    givenRecommendation = models.CharField(max_length=5555, null=True, blank=True)
    givenRecommendationCount = models.CharField(max_length=5555, null=True, blank=True)
    receivedRecommendation = models.CharField(max_length=5555, null=True, blank=True)
    receivedRecommendationCount = models.CharField(
        max_length=5555, null=True, blank=True
    )
    courses = models.CharField(max_length=5555, null=True, blank=True)
    certifications = models.CharField(max_length=5555, null=True, blank=True)
    honors = models.JSONField(null=True, blank=True)
    projects = models.JSONField(null=True, blank=True)
    volunteering = models.CharField(max_length=5555, null=True, blank=True)
    supportedLocales = models.JSONField(null=True, blank=True)
    multiLocaleFirstName = models.JSONField(null=True, blank=True)
    multiLocaleLastName = models.JSONField(null=True, blank=True)
    multiLocaleHeadline = models.JSONField(null=True, blank=True)

    def __str__(self):
        return f"{self.broker} - {self.urn}"


class BrokerScrappingData(models.Model):
    broker_linkedin_profile = models.ForeignKey(
        BrokersLinkedInProfileData, on_delete=models.CASCADE
    )
    content = models.JSONField(null=True, blank=True)

    def __str__(self):
        return f"{self.broker_linkedin_profile.broker.crd} - {self.broker_linkedin_profile.username}"
