from django.db import models


class Brokers(models.Model):
    crd = models.CharField(max_length=255)
    npm = models.CharField(max_length=255)
    firstName = models.CharField(max_length=255)
    middleName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255)
    otherNames = models.CharField(max_length=255)
    team = models.CharField(max_length=255)
    brokerDealer = models.CharField(max_length=255)
    brokerDealerCRD = models.CharField(max_length=255)
    yearsWithCurrentBD = models.CharField(max_length=255)
    currentBDStartDate = models.DateTimeField(null=True, blank=True)
    ria = models.CharField(max_length=255)
    riaCRD = models.CharField(max_length=255)
    yearsWithCurrentRIA = models.CharField(max_length=255)
    currentRIAStateDate = models.DateTimeField(null=True, blank=True)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zip = models.CharField(max_length=255)
    metroArea = models.CharField(max_length=255)
    licensesAndExams = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    designations = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    phone_type = models.CharField(max_length=255)
    linkedIn = models.CharField(max_length=255)
    email1 = models.CharField(max_length=255)
    email2 = models.CharField(max_length=255)
    email3 = models.CharField(max_length=255)
    personalEmail = models.CharField(max_length=255)
    bio = models.CharField(max_length=255)
    yearsOfExperience = models.CharField(max_length=255)
    estAge = models.CharField(max_length=255)
    previousBrokerDealer = models.CharField(max_length=255)
    previousRIA = models.CharField(max_length=255)
    gender = models.CharField(max_length=255)
    teamId = models.CharField(max_length=255)
    personTagRole = models.CharField(max_length=255)
    personTagFamily = models.CharField(max_length=255)
    personTagHobbies = models.CharField(max_length=255)
    personTagExpertise = models.CharField(max_length=255)
    personTagServices = models.CharField(max_length=255)
    personTagInvestments = models.CharField(max_length=255)
    personTagSportsTeams = models.CharField(max_length=255)
    personTagSchool = models.CharField(max_length=255)
    personTagGreekLife = models.CharField(max_length=255)
    personTagMilitaryStatus = models.CharField(max_length=255)
    personTagFaithBasedInvesting = models.CharField(max_length=255)
    firmTagPlatform = models.CharField(max_length=255)
    firmTagTechnology = models.CharField(max_length=255)
    firmTagServices = models.CharField(max_length=255)
    firmTagInvestments = models.CharField(max_length=255)
    firmTagCustodian = models.CharField(max_length=255)
    firmTagClients = models.CharField(max_length=255)
    firmTagCRM = models.CharField(max_length=255)
    notes = models.CharField(max_length=255)
    profile = models.CharField(max_length=255)
    secLink = models.CharField(max_length=255)
    finraLink = models.CharField(max_length=255)
    firmCompanyName = models.CharField(max_length=255)
    firmType = models.CharField(max_length=255)
    firmAddress = models.CharField(max_length=255)
    firmCity = models.CharField(max_length=255)
    firmState = models.CharField(max_length=255)
    firmZip = models.CharField(max_length=255)
    firmPhone = models.CharField(max_length=255)
    firmAUM = models.CharField(max_length=255)
    firmTotalAccounts = models.CharField(max_length=255)
    firmCustodians = models.CharField(max_length=255)
    firmTotalEmployees = models.CharField(max_length=255)
    firmRIAReps = models.CharField(max_length=255)
    firmBDReps = models.CharField(max_length=255)
    firmForm13f = models.CharField(max_length=255)
    lines = models.CharField(max_length=255)
    carrier = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    initialAppointmentDate = models.CharField(max_length=255)
    captive = models.CharField(max_length=255)
    numOfCarriers = models.CharField(max_length=255)
    numOfLines = models.CharField(max_length=255)
    nonProducing = models.CharField(max_length=255)
    insuranceYearsOfExperience = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.crd} - {self.firstName} {self.middleName} {self.lastName}"


class BrokersLinkedInProfileData(models.Model):
    broker = models.ForeignKey(Brokers, on_delete=models.CASCADE)
    urn = models.CharField(max_length=255)
    username = models.CharField(
        max_length=255,
    )
    firstName = models.CharField(max_length=255, null=True, blank=True)
    lastName = models.CharField(max_length=255, null=True, blank=True)
    isOpenToWork = models.BooleanField(null=True, blank=True)
    isHiring = models.BooleanField(null=True, blank=True)
    profilePicture = models.URLField(null=True, blank=True)
    summary = models.CharField(max_length=255, null=True, blank=True)
    headline = models.CharField(max_length=255, null=True, blank=True)
    geo = models.JSONField(null=True, blank=True)
    languages = models.CharField(max_length=255, null=True, blank=True)
    educations = models.JSONField(null=True, blank=True)
    position = models.JSONField(null=True, blank=True)
    fullPositions = models.JSONField(null=True, blank=True)
    skills = models.JSONField(null=True, blank=True)
    givenRecommendation = models.CharField(max_length=255, null=True, blank=True)
    givenRecommendationCount = models.CharField(max_length=255, null=True, blank=True)
    receivedRecommendation = models.CharField(max_length=255, null=True, blank=True)
    receivedRecommendationCount = models.CharField(
        max_length=255, null=True, blank=True
    )
    courses = models.CharField(max_length=255, null=True, blank=True)
    certifications = models.CharField(max_length=255, null=True, blank=True)
    honors = models.JSONField(null=True, blank=True)
    projects = models.JSONField(null=True, blank=True)
    volunteering = models.CharField(max_length=255, null=True, blank=True)
    supportedLocales = models.JSONField(null=True, blank=True)
    multiLocaleFirstName = models.JSONField(null=True, blank=True)
    multiLocaleLastName = models.JSONField(null=True, blank=True)
    multiLocaleHeadline = models.JSONField(null=True, blank=True)

    def __str__(self):
        return f"{self.broker} - {self.urn}"
